version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bookomol"
s3_bucket = ""  # Will be created by SAM CLI on first deployment
s3_prefix = "bookomol"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=dev TelegramBotToken=\"\" DatabasePassword=\"\""

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "bookomol-prod"
parameter_overrides = "Environment=prod TelegramBotToken=\"\" DatabasePassword=\"\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = false